name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to GitHub Packages
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change package scope
        run: |
          sed -ibak -E "s/@.+(\/templatetemplate)/${{ github.repository_owner }}\1/"
          cat package.json
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: lts/hydrogen
      #     cache: npm
      #     registry-url: https://npm.pkg.github.com
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
